@startuml 

title Food Delivery Application\nClass Diagram

class User {
    UserID : Integer
    method()
}

class RestaurantList {
    RestaurantListID : Integer
    RestaurantList : Restaurant[]
    getRestaurantList()
    FilterList()

}

class Restaurant {
    RestaurantID : Integer
    OwnerID : Integer
    Location : String
    IsNonVeg : Bool
    Rating : Integer
    Popularity : PopularityRating
    Registration : RegisrationStatus
    GetDeliveryTime() : Datetime
    GetMenu(RestaurantID) : Menu
}

Restaurant -right-> PopularityRating

enum PopularityRating {
    1 Star
    2 Star
    3 Star
    4 Star
    5 Star
}

Restaurant -right-> RegisrationStatus

enum RegisrationStatus {
    New 
    Accepted
    Rejected
}

class Menu {
    MenuID : Integer
    RestaurantID : Integer
    CreateCart(UserID)
    GetMenu(RestaurantID)
    AddItemToCart(ItemID)
}

class Cart {
    CartID : Integer
    UserID : Integer
    RestaurantID : Integer
    CartInstructions : String
    CartItems : Item[]
    CalculateSubTotal(CartItems) : Double
    CreateOrder(Cart)
}

class Order {
    OrderID : Integer
    UserID : Integer
    RestaurantID : Integer
    OrderItems : CartItems
    ValidateDiscount()
    ApplyDiscount()
    CalculateTax()
    CalculateDeliveryFee()
    CalculateTotal(OrderItems,CalculateTax(),ApplyDiscount())
}

class Payment {
    PaymentID : Integer
    UserID : Integer
    RestaurantID : Integer
    OrderID : Integer
    PaymentType : PaymentType
    Total : Double
    SubTotal : Double
    Tax : Double
    DeliveryFee : Double
    SubmitPayment()
    InitiateOrder(OrderID)
    GetOrders(UserID)
}

class Reciept {
    RecieptID : Integer
    PaymentID : Integer
    UserID : Integer
    RestaurantID : Integer
    OrderID : Integer
    PaymentType : PaymentType
    Total : Double
    SubTotal : Double
    Tax : Double
    DeliveryFee : Double
}

class Notification {
    NotificationID : Integer
    NotificationType : Notification
    SendNotification()
}

class NotificationStatus {
    field : String
    method()
}

@enduml 