@startuml
header Learn and Design 2023 - POD 1
footer Page %page% of %lastpage%
title: Food Delivery Application - Consumer Use Case Diagram

skinparam actorStyle awesome

left to right direction

actor Consumer #blue;line:blue

Package Restaurant {
    Consumer -[#blue]-> (Find Restaurant)
    Consumer -[#blue]-> (Select Restaurant)
}

Package Menu {
    Consumer -[#blue]-> (View Menu Items)
    Consumer -[#blue]-> (Select Menu Items)
}

Package Cart {
    Consumer -[#blue]-> (Add Items to Cart)
    Consumer -[#blue]-> (Edit Cart)
}

Package Order {
    Consumer -[#blue]-> (Submit Order)
    Consumer -[#blue]-> (Process Order)
    Consumer -[#blue]-> (Process Payment)
    Consumer -[#blue]-> (Delivery Order)
    Consumer -[#blue]-> (Cancel Order)
}

package Refund {
    Consumer -[#blue]-> (Request Refund)
    Consumer -[#blue]-> (Notify Refund)
    Consumer -[#blue]-> (View Refund)
}

@enduml