@startuml
left to right direction
skinparam packageStyle rectangle
actor Consumer
actor RestaurantOwner
actor ApplicationManager

rectangle checkout {
  Consumer -- (Home)
  (checkout) .> (payment) : include
  (help) .> (checkout) : extends
  (checkout) -- ApplicationManager
}
@enduml